library(igraph)
library(igraphdata)

# This graph is a representation of the mesh network being built by the NYC Mesh organization, as recorded on Jan. 28th, 2019 on at https://www.nycmesh.net/map/. Each vertex represents a router node that is connected to the mesh network through dish or antenna installations. The "supernodes" have reserved space on internet-exchange cables that allow the mesh network to connect to the larger Internet. Each edge is an explicit "over-the-air" connections made between nodes. Other network connections through simple proximity or through the city's LinkNYC kiosks are not represented. This data does not represent the geographical proximity of vertices or components, merely whether nodes are attached to the NYC mesh network at all. Isolated smaller nodes (that can "tunnel" through the Internet to access the mesh) have not been included in the graph, although they represent approximately half the overall nodes in the network.
# Graph Characteristics:
#   Edges: 127, Vertices: 129, 
#   Graph Density: 0.01538275, 
#   Mean Degree of Vertices: 1.968992 

# define connected nodes (w/ edges)
edges = c("Supernode 1","1971",
          "Supernode 1","Henry",
          "Supernode 1", "650",
          "650", "836",
          "Supernode 1", "593",
          "Supernode 1", "1625",
          "Supernode 1", "1440",
          "Supernode 1", "1496",
          "Supernode 1", "1275",
          "Supernode 1", "2153",
          "Supernode 1", "561",
          "Supernode 1", "2088",
          "Supernode 1", "2415",
          "Supernode 1", "2006",
          "Supernode 1", "2554",
          "Supernode 1", "2663",
          "Supernode 1", "2688",
          "Supernode 1", "1327",
          "Supernode 1", "555",
          "Supernode 1", "2350",
          "Supernode 1", "699",
          "Supernode 1", "2537",
          "1971", "2404",
          "Supernode 1", "662",
          "Supernode 1", "1401",
          "Supernode 1", "1138",
          "Supernode 1", "468",
          "Supernode 1", "1627",
          "Supernode 1", "729",
          "Supernode 1", "565",
          "Rivington", "1497",
          "Rivington", "2537", 
          "Rivington", "2814", 
          "Rivington", "556",
          "Rivington", "2539",
          "Rivington", "2821",
          "Rivington", "19",
          "Rivington", "2590",
          "Rivington", "1430",
          "Supernode 1", "2745",
          "Supernode 1", "1660",
          "Supernode 1", "1854",
          "Supernode 1", "1201",
          "Supernode 1", "1167",
          "Supernode 1", "2111",
          "Supernode 1", "1992",
          "Supernode 1", "467",
          "Supernode 1", "2279",
          "467", "7",
          "7", "330",
          "330", "3",
          "3", "7",
          "101A", "2786",
          "Pierre", "201",
          "1147", "2079",
          "Supernode 1", "1612",
          "3", "1258",
          "3", "201",
          "Henry","659",
          "Henry", "Rivington", 
          "Supernode 1", "1384",
          "Rivington", "7th St.",
          "7th St.", "Pierre",
          "Supernode 1", "1147",
          "100A", "Rivington",
          "Supernode 1", "Domino",
          "Domino", "Simona",
          "Simona", "1606",
          "Simona", "229",
          "Simona", "354",
          "354", "1923",
          "354", "Soft Surplus",
          "Soft Surplus", "323",
          "Soft Surplus", "2335",
          "Soft Surplus", "355",
          "Soft Surplus", "1189",
          "Soft Surplus", "2287",
          "Soft Surplus", "Cypress Inn",
          "Cypress Inn", "2071",
          "Cypress Inn", "2794",
          "Cypress Inn", "2192",
          "Cypress Inn", "2098",
          "Cypress Inn", "Saratoga",
          "Soft Surplus", "Saratoga",
          "Saratoga", "Dekalb",
          "Dekalb", "1946",
          "Saratoga", "Troutman",
          "Troutman", "529",
          "Saratoga", "1583",
          "Saratoga", "1294",
          "Saratoga", "1893",
          "Saratoga", "324",
          "Saratoga", "1524",
          "Saratoga", "2148",
          "Saratoga", "2058",
          "Saratoga", "1659",
          "Saratoga", "1599",
          "Saratoga", "1533",
          "Saratoga", "1825",
          "Saratoga", "2387",
          "Saratoga", "740",
          "Saratoga", "667",
          "Saratoga", "2291",
          "Saratoga", "2131",
          "Saratoga", "2083",
          "Saratoga", "1546",
          "Saratoga", "1779",
          "Saratoga", "627",
          "Saratoga", "2174",
          "Saratoga", "2647",
          "Saratoga", "1776",
          "Saratoga", "2039",
          "Saratoga", "1085",
          "Saratoga", "1795",
          "Saratoga", "2101",
          "Saratoga", "1710",
          "Saratoga", "1862",
          "Saratoga", "Ehud",
          "Saratoga", "1916",
          "Saratoga", "Flo",
          "Flo", "760",
          "Flo", "2623",
          "Saratoga", "Supernode 4",
          "Supernode 4", "2596",
          "844", "2699",
          "844", "2090",
          "844", "2223")
# create graph, along with isolate hub & supernode vertices
nycMesh <- graph(edges, isolates = c("Supernode 3", "363", "1126"), directed=FALSE)

# set vertex type. "Active Node" is the most common"
V(nycMesh)$nodeType <- c("Active Node")
vertex_attr(nycMesh, "nodeType", V(nycMesh)["Supernode 1", "Supernode 3", "Supernode 4"]) <- "Supernode"
vertex_attr(nycMesh, "nodeType", V(nycMesh)["1971", "Henry","659","Rivington","1384", "7th St.","Pierre","1147","100A", "Domino", "Simona", "Soft Surplus", "Cypress Inn", "Saratoga", "Dekalb", "Troutman", "Ehud", "1916", "Flo", "844", "363", "1126"]) <- "Hub"

# set display size of vertices
V(nycMesh)$size=degree(nycMesh)/1.5

# output network as graph
plot(nycMesh, 
     frame.color="white", 
     vertex.color="skyblue", 
     vertex.frame.color=NA, 
     edge.color="grey", 
     vertex.label.family="Inconsolata", 
     vertex.label.cex=.6, 
     width=20)

print("This graph is a representation of the mesh network being built by the NYC Mesh organization, as recorded on Jan. 28th, 2019 on at https://www.nycmesh.net/map/. Each vertex represents a router node that is connected to the mesh network through dish or antenna installations. The 'supernodes' have reserved space on internet-exchange cables that allow the mesh network to connect to the larger Internet. Each edge is an explicit 'over-the-air' connections made between nodes. Other network connections through simple proximity or through the city's LinkNYC kiosks are not represented. This data does not represent the geographical proximity of vertices or components, merely whether nodes are attached to the NYC mesh network at all. Isolated smaller nodes (that can 'tunnel' through the Internet to access the mesh) have not been included in the graph, although they represent approximately half the overall nodes in the network.")

# print underlying matrices
options(max.print= 10000, width = 10000)
print(as_adjacency_matrix(nycMesh))
print(as_edgelist(nycMesh))
